config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :housekeepings
  get 'home/index'
  get 'home/about'

  # declare own devise controller
  devise_for :users, controllers: { registrations: "registrations"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index' #TODO needs to be changed
  telegram_webhooks TelegramWebhookController

  # only allow authenticated users to view sidekiq
  authenticate :user do
  mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      # or
    #can :manage, Housekeeping do |housekeeping|
    #housekeeping.user_id == user.id
    #end


    #alias_action :read, :update, :destroy, to: :rud
    #can :create, Housekeeping
    can :show, Housekeeping, user_id: user.id
    can :delete, Housekeeping, user_id: user.id
    can :update, Housekeeping, user_id: user.id
    can :destroy, Housekeeping, user_id: user.id

      #can :update, Housekeeping

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event_occurrence.rb
class EventOccurrence < ActiveRecord::Base
  belongs_to :schedulable, polymorphic: true
  default_scope lambda{order('date ASC')}
  scope :remaining, lambda{where(["date >= ?",Time.now])}
  scope :previous, lambda{where(["date < ?",Time.now])}
  scope :today, lambda{where(:date => Time.now...Time.now.end_of_day)}
  scope :week, lambda{where(:date => Time.now...7.days.from_now)}
  scope :tomorrow, lambda{where(:date => Time.now.tomorrow.beginning_of_day...Time.now.tomorrow.end_of_day)}
  scope :month, lambda{where(:date => Time.now...30.days.from_now)}
  #scope :telegramid, ->(users) { where(users: object.id) }
  #scope :with_telegramid, -> (telegramid) {joins(:users).merge(User.where(telegram_id: telegramid))}
end

app/models/housekeeping.rb
class Housekeeping < ApplicationRecord
  acts_as_schedulable :schedule, occurrences: :event_occurrences

  belongs_to :user
end

app/models/schedule.rb
class Schedule < Schedulable::Model::Schedule
end

app/models/user.rb
class User < ApplicationRecord
  # TODO: Add Role Support
  # TODO:
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :housekeepings
  has_many :event_occurrences, through: :housekeepings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me, :login, :telegram_id]
    devise_parameter_sanitizer.permit(:sign_up,  keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
    #devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :login, :password, :remember_me])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/housekeepings_controller.rb
class HousekeepingsController < ApplicationController
  before_action :set_housekeeping, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # manage authorization
  #load_and_authorize_resource :only => [:index, :show, :edit, :update, :destroy]
  #skip_authorize_resource :only => [:new, :remember, :create]

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message


  end
  # GET /housekeepings
  # GET /housekeepings.json
  def index
    @housekeepings = current_user.housekeepings
  end

  # GET /housekeepings/1
  # GET /housekeepings/1.json
  def show
    authorize! :show, @housekeeping
  end

  # GET /housekeepings/new
  def new
    @housekeeping = Housekeeping.new
  end

  # GET /housekeepings/1/edit
  def edit
  end

  # POST /housekeepings
  # POST /housekeepings.json
  def create
    #@housekeeping = Housekeeping.new(housekeeping_params)
    #@housekeeping.user = current_user
    @housekeeping = current_user.housekeepings.new(housekeeping_params)
    respond_to do |format|
      if @housekeeping.save
        format.html { redirect_to @housekeeping, notice: I18n.t('housekeeping.created')}
        format.json { render :show, status: :created, location: @housekeeping }
      else
        format.html { render :new }
        format.json { render json: @housekeeping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /housekeepings/1
  # PATCH/PUT /housekeepings/1.json
  def update
    authorize! :update, @housekeeping
    respond_to do |format|
      if @housekeeping.update(housekeeping_params)
        format.html { redirect_to @housekeeping, notice: I18n.t('housekeeping.updated') }
        format.json { render :show, status: :ok, location: @housekeeping }
      else
        format.html { render :edit }
        format.json { render json: @housekeeping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /housekeepings/1
  # DELETE /housekeepings/1.json
  def destroy
    authorize! :destroy, @housekeeping
    @housekeeping.destroy
    respond_to do |format|
      format.html { redirect_to housekeepings_url, notice: t('housekeeping.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_housekeeping
      @housekeeping = Housekeeping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def housekeeping_params
      params.require(:housekeeping).permit(:name, :descr, :remember, schedule_attributes: Schedulable::ScheduleSupport.param_names)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((User.count == 1) & (user_signed_in?))
      #redirect_to root_path
    elsif User.count == 1
      #redirect_to new_user_session_path
    end
  end

end

app/controllers/reminder_controller.rb
class ReminderController < ApplicationController
  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/housekeepings_helper.rb
module HousekeepingsHelper
end

app/views/home/about.erb
<div class="page-header">
  <h1>Über diese App</h1>
</div>
<p><h3><b><i>Private Remembrall App</i></b></h3></p>
<p><i>Um was gehts in dieser App und was kann sie?</i></br>
Remembrall ist dazu gedacht die alltäglichen Dinge des Lebens
besser in den Griff zu bekommen.</br>
Sie richtet sich zielgerecht an Menschen mit psychischer Beeinträchtigung,
welchen es meist schwer fällt diese Dinge zu bewältigen.</br>
Aus eigenen Erfahrungen ist es jedoch einfacher, diese Dinge mittels Smartphone-Erinnerung
in den Griff zu bekommen.</br>
Die entsprechenden Einträge können bequem am heimischen PC bearbeitet und
dann mittels Telegram abgerufen werden.Hierzu werden die sog. Bots von Telegram in Anspruch
genommen.</p>
</br>
</br>
<p><i>Wie benutze ich die App?</i></br>
Um dieses Programm benutzen Sie können, benötigen Sie erst einmal lediglich folgende Dinge:</br>
<ul>
	<li>Einen Rechner mit Internet-Verbindung</li>
	<li>Ein Smartphone mit installiertem Telegram-Messenger</li>
	<li>Die Gewissheit ob sie die App auf einem Windows oder Linux-Rechner verwenden wollen</li>
	<li>Grundlegende Kenntnisse in den zuvor genannten Punkten ;-) </li>
	<li>....und natürlich viel Spaß an der Freud ^^</li>
</ul>
</p>
</br>
</br>
<p><i>Wie richte ich die App ein?</i></br>
Gehen wir davon aus das sie einen Windoof-Rechner benutzen, wie soviele andere ihrer Mitmenschen auch,
dann gehen sie folgendermaßen vor:</br>
<ol>
	<li>Download des Archives bei <a href="http://struenzer.bplaced.de/index.php?option=com_jdownloads&view=download&id=3:remebrall_thiago&catid=3&Itemid=184" tagret=_blank>
	BFLmedia</a></li>
	<li>Entpacken des Zip-Archives auf deinem Rechner</li>
	<li>Anlegen eines Bots in Telegram ( /newbot an BotFather senden)</li>
	<li>Bot nach eigenen Wünschen anpassen</li>
	<li>ID des Bots auslesen ( /telegramid an Bot senden)</li>
	<li><a href="https://github.com/railsinstaller/railsinstaller-windows" target=_blank>
	Railsinstaller</a> herunterladen und installieren</li>
	<li>nun zwei "Prompt-Fenster" öffnen und in einem "rails s" und im anderen "rake telegram:bot:poller"</li>
	<li>Browser öffnen und zur Seite http://localhost:3000 navigieren</li>
	<li>Auf der sich nun öffnenden Seite unter Login->Registrieren einen neuen Account anlegen</li>
	<li>Nun unter Profil bearbeiten->Telegram ID die zuvor ausgelesene ID des Bots eintragen!</li>
	<b>FERTIG!</b> Die App ist nun funktionsbereit!</br>
	<li>Nun einmal ein paar Testeinträge unter Module->Haushaltsplan anlegen und versuchen
	diese über den Telegram-Messenger ab zu rufen. ( /housekeeping im Bot eingeben)</li>
	<li>Geldbeutel checken!</li>
	<li>Paypal-Konto checken!</li>
	<li>Konto-Auszüge checken!</li>
	<li>Überlegen ob einem dieses nette "Äppschen" nicht eine kleine Spende an die Entwickler
	wert sein dürfte ;-)</li>
	
</ol>
</p>
</br>
</br>
<p><i>Wo bekomme ich Hilfe wenn ich einmal nicht weiterkommen sollte?</i></br>
Sollten sie einmal nicht mehr weiter kommen oder Probleme/Fragen
auftreten dann posten Sie doch einfach in unserem <a href="http://struenzer.bplaced.de/index.php?option=com_kunena&view=category&catid=15&Itemid=243" target=_blank>
Supportforum"</a></br>
In dringenden Fällen können Sie uns auch direkt kontaktieren, wie dies geht erfahren Sie ebenfalls
auf den Seiten von <a href="http://www.bflmedia.rockt.es" target=_blank>BFLmedia</a>
</p>

app/views/home/index.html.erb
<div class="page-header">
<h2>Willkommen!</h2>
</div>
<p>Dies ist die Beta-Version von Remembrall V1.0</p>
<p>Fragen rund um die Handhabung und Bedienung können Sie gerne jederzeit in unserem
<a href="http://struenzer.bplaced.de/index.php?option=com_kunena&view=category&catid=15&Itemid=243" target="_blank">
Supportforum</a> bei <a href="https://www.facebook.com/BFLmedia" target=_blank>BFLmedia</a> stellen.</p>

app/views/housekeepings/_form.html.erb
<%= simple_form_for(@housekeeping) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :descr, label: 'Beschreibung' %>
    <%= f.input :schedule, as: :schedule, label: 'Fällig' %>
    <%= f.input :remember, label: 'Erinnern' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<script type="text/javascript">
    $("option[value='singular']").remove();
    </script>

app/views/housekeepings/edit.html.erb
<div class="page-header">
<h1>Eintrag bearbeiten</h1>
</div>
<%= render 'form', housekeeping: @housekeeping %>
<p>
<%= link_to 'Zurück', housekeepings_path %> |
  <%= link_to 'Anzeigen', @housekeeping %></p>

app/views/housekeepings/index.html.erb
<div class="page-header">
<h2>Haushaltsplan</h2>
</div>
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Fällig</th>
    <th>Uhrzeit</th>
    <th>Erinnern</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @housekeepings.each do |housekeeping| %>
      <tr>
        <td><%= housekeeping.name %></td>
        <td><%= housekeeping.schedule %></td>
        <td><%= housekeeping.schedule.time.strftime('%H:%M Uhr') %></td>
        <td><%= t(housekeeping.remember.to_s) %></td>
        <td><%= link_to t('housekeeping.show'), housekeeping %></td>
        <td><%= link_to t('housekeeping.edit'), edit_housekeeping_path(housekeeping) %></td>
        <td>
          <%= link_to t('housekeeping.destroy'), housekeeping, method: :delete, data: {confirm: t('housekeeping.confirm_message')},
                      'data-confirm-fade' => true, 'data-confirm-title' => t('housekeeping.confirm_title'),
                      'data-confirm-cancel-class' => 'btn btn-default',
                      'data-confirm-cancel' => 'Nein',
                      'data-confirm-proceed-class' => 'btn btn-danger',
                      'data-confirm-proceed' => 'Ja'
          %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Neuer Eintrag', new_housekeeping_path, class: 'btn btn-default' %>

app/views/housekeepings/new.html.erb
<div class="page-header">
<h2>Eintrag zum Haushaltsplan hinzufügen</h2>
</div>
<%= render 'form', housekeeping: @housekeeping %>

<%= link_to 'Zurück', housekeepings_path %>

app/views/housekeepings/show.html.erb
  <div class="page-header"><h1>Plan</h1></div>
<div class="panel panel-default">
  <div class="panel-body">


      <div class="col-md-2">
      <strong>Name:</strong>
      </div>
      <div class="col-md-10">
    <%= @housekeeping.name %>
      </div>

    <br/>
    <div class="col-md-2">
      <strong>Beschreibung:</strong>
    </div>
    <div class="col-md-10">
      <p> <%= @housekeeping.descr %> &nbsp;</p>
    </div>


    <div class="col-lg-2">
      <strong>Fällig:</strong>
    </div>
    <div class="col-lg-10">
      <%= @housekeeping.schedule %>
    </div>

    <div class="col-lg-2">
      <strong>Uhrzeit:</strong>
    </div>
    <div class="col-lg-10">
      <%= I18n.l(@housekeeping.schedule.time, format: :short) %>
    </div>

    <p class="col-lg-2">
      <strong>Erinnern:</strong>
    </p>
    <div class="col-lg-10">
      <%= t(@housekeeping.remember.to_s) %>
    </div>

  </div>

  <div class="panel-footer">
    <%= link_to 'Zurück', housekeepings_path %>|
    <%= link_to 'Bearbeiten', edit_housekeeping_path(@housekeeping) %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Remembrall" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= nav_bar static: :top, brand: "Remembrall V1.0", :inverse => true, class: 'navbar-inverse'   do %>

      <%= menu_group do %>
          <%= menu_item "Home", root_path %>
          <%= menu_divider %>
          <%= menu_item "About", home_about_path %>
          <% if user_signed_in? %>
              <%= drop_down "Module" do %>
                  <%= menu_item "Haushaltsplan", housekeepings_path %>
              <% end %>
          <% end %>
      <% end %>
      <%= menu_group pull: :right do %>
          <% if user_signed_in? %>
              <%= menu_text "Hallo #{current_user.username}" %>
              <%= menu_item 'Profil bearbeiten', edit_user_registration_path %>
              <%= menu_divider %>
              <%= menu_item "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
              <%= menu_item "Login", new_user_session_path %>
          <% end %>

      <% end %>

  <% end %>

  <!--
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Remembrall</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><#%= link_to "Link1", "/path1"  %></li>
            <li><#%= link_to "Link2", "/path2"  %></li>
            <li><#%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>-->

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <div class="panel panel-default">
            <div class="panel-body">
          <%= yield %>
            </div>
          </div>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Thiago Zimmermann 2017 - supported by BFLmedia-Bernd Fischer</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>
<% if Rails.env.development? %>
<% console %>
<% end %>